### PR TITLE
Penalized regression on concrete-ml

### PR DESCRIPTION
**Pull request by MahmoudMohajer**
It is a tutorial to teach how to apply Lasso, Ridge, and ElasticNet on concrete-ml from an absolute beginner perspective.

### CODE REVIEW

**Comment by MahmoudMohajer** [comment]
I have started working on apply the mentioned improvements.

**Comment by MahmoudMohajer** [comment]
Thank you for your feedback. I have implemented all of the requested improvements in the notebook, except for the timing section which I intentionally left out to maintain a manageable notebook size. If you think that including timing is necessary, I would be happy to add it. Please let me know if you have any further comments or suggestions.

**Comment by MahmoudMohajer** [comment]
Thank you for your feedback. I have incorporated your suggestions into the notebook. I added a section that compares the performance metric for various values of the parameter n_bits and included a visualization of the results. I also included a real dataset in the notebook to demonstrate how the model can be applied in a real-world scenario. Additionally, I included a timing function to show the speed of the FHE models and added a visualization to compare the Concrete-ML model with the sklearn model. Please let me know if there are any further improvements or suggestions. Thank you.

**Comment by fd0r** [comment]
Hello @MahmoudMohajer , thanks a lot for your PR!
We won't be adding it to our repository for now, as we don't see the need for another tutorial about linear models.
Cheers

**Pull request closed without merging**
