### PR TITLE
docs: add regressor comparison in concrete-ml context tutorial

### PR DESCRIPTION
**Pull request by AmT42**

### CODE REVIEW

**Review by jfrery — COMMENTED** [review]
Thanks for the PR. The notebook is well written and the visualization are great!

We have just one comment before we can proceed and have the PR on concrete-ml for a more in-depth review.

It seems that you are pre-processing the input differently for the linear models. This gives the illusion that linear models outperform the other models. Could you make the pre-processing similar for all models?

**Comment by fd0r** [comment]
Hello @AmT42 , thanks a lot for your contribution!

Could you open a PR with the notebook in the folder docs/advanced_examples on the branch https://github.com/zama-ai/concrete-ml/tree/tutorials please?
Using [CapitalizedWords](https://en.wikipedia.org/wiki/Camel_case) for the name of the notebook.

Once the PR is merged in the branch with the other bounty contributions we will procede to merge it on main and your work will be featured in the next release!

**Comment by AmT42** [comment]
Done here [PR](https://github.com/zama-ai/concrete-ml/pull/70/commits/1e7e2f28a6f9edf3d6a42c6bc77cb36c3846b03d).
I also made few modification to adapte it to concrete 1.0

**Comment by aquint-zama** [comment]
everything merged, closing.

**Pull request closed without merging**
